services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend:latest
    container_name: bd_cw_osrm
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    command: osrm-routed --algorithm mld /data/ukraine-latest.osrm
    restart: unless-stopped
