"""init schema

Revision ID: 3559291aa6b6
Revises:
Create Date: 2026-04-06 18:44:24.788999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3559291aa6b6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("city", sa.String(length=128), nullable=False),
        sa.Column("street", sa.String(length=255), nullable=False),
        sa.Column("building", sa.String(length=32), nullable=False),
        sa.Column("apartment", sa.String(length=32), nullable=True),
        sa.Column("coordinates", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
    )
    op.create_table(
        "transports",
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column(
            "type",
            sa.Enum("bike", "scooter", "car", "van", "truck", name="transport_type"),
            nullable=False,
        ),
        sa.Column("max_weight", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("max_volume", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transports")),
    )
    op.create_table(
        "users",
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_users_phone")),
    )
    op.create_table(
        "admins",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_admins_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_admins")),
    )
    op.create_table(
        "clients",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_clients_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_clients")),
    )
    op.create_table(
        "couriers",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("transport_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "rating_avg",
            sa.Numeric(precision=3, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["transport_id"],
            ["transports.id"],
            name=op.f("fk_couriers_transport_id_transports"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_couriers_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_couriers")),
    )
    op.create_table(
        "orders",
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "assigned",
                "picked_up",
                "in_transit",
                "delivered",
                "cancelled",
                name="order_status",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("weight", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("volume", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("scheduled_pickup_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "scheduled_delivery_time", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("special_instructions", sa.String(length=1000), nullable=True),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column("courier_id", sa.Integer(), nullable=True),
        sa.Column("pickup_address_id", sa.Integer(), nullable=False),
        sa.Column("delivery_address_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["couriers.user_id"],
            name=op.f("fk_orders_courier_id_couriers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["delivery_address_id"],
            ["addresses.id"],
            name=op.f("fk_orders_delivery_address_id_addresses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pickup_address_id"],
            ["addresses.id"],
            name=op.f("fk_orders_pickup_address_id_addresses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["clients.user_id"],
            name=op.f("fk_orders_recipient_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["clients.user_id"],
            name=op.f("fk_orders_sender_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_table(
        "payments",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum("cash", "card", "online", name="payment_method"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_payments_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("order_id", name=op.f("uq_payments_order_id")),
    )
    op.create_table(
        "reviews",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "rating BETWEEN 1 AND 5", name=op.f("ck_reviews_rating_range")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_reviews_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("order_id", name=op.f("uq_reviews_order_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reviews")
    op.drop_table("payments")
    op.drop_table("orders")
    op.drop_table("couriers")
    op.drop_table("clients")
    op.drop_table("admins")
    op.drop_table("users")
    op.drop_table("transports")
    op.drop_table("addresses")
    # ### end Alembic commands ###
