"""review per author

Revision ID: 393211fec026
Revises: f0c496ce0b82
Create Date: 2026-04-09 16:57:06.983722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "393211fec026"
down_revision: Union[str, Sequence[str], None] = "f0c496ce0b82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("reviews", sa.Column("author_user_id", sa.Integer(), nullable=True))
    # Backfill: existing reviews are attributed to the order's sender.
    op.execute(
        "UPDATE reviews r SET author_user_id = o.sender_id "
        "FROM orders o WHERE r.order_id = o.id"
    )
    op.alter_column("reviews", "author_user_id", nullable=False)
    op.drop_constraint(op.f("uq_reviews_order_id"), "reviews", type_="unique")
    op.create_unique_constraint(
        "uq_review_order_author", "reviews", ["order_id", "author_user_id"]
    )
    op.create_foreign_key(
        op.f("fk_reviews_author_user_id_users"),
        "reviews",
        "users",
        ["author_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_reviews_author_user_id_users"), "reviews", type_="foreignkey"
    )
    op.drop_constraint("uq_review_order_author", "reviews", type_="unique")
    op.create_unique_constraint(
        op.f("uq_reviews_order_id"),
        "reviews",
        ["order_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("reviews", "author_user_id")
    # ### end Alembic commands ###
