"""add_orders_is_confirmed_and_created_by

Revision ID: f0c496ce0b82
Revises: dd70e1bb94f2
Create Date: 2026-04-09 13:39:15.562125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0c496ce0b82"
down_revision: Union[str, Sequence[str], None] = "dd70e1bb94f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("is_confirmed", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "orders", sa.Column("created_by_user_id", sa.Integer(), nullable=True)
    )
    # Backfill existing rows with sender_id so NOT NULL can be applied.
    op.execute(
        "UPDATE orders SET created_by_user_id = sender_id WHERE created_by_user_id IS NULL"
    )
    op.alter_column("orders", "created_by_user_id", nullable=False)
    op.create_foreign_key(
        op.f("fk_orders_created_by_user_id_users"),
        "orders",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_orders_created_by_user_id_users"), "orders", type_="foreignkey"
    )
    op.drop_column("orders", "created_by_user_id")
    op.drop_column("orders", "is_confirmed")
    # ### end Alembic commands ###
